config/routes.rb
Rails.application.routes.draw do
	root 'todo#index'
  	get 'todo/index'
  	get 'todo/:id/update' => 'todo#update'
  	post 'todo/create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :todos
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project
  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todo_controller.rb
class TodoController < ApplicationController
  def index
  	@projects = Project.all
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.isCompleted == false then
      @todo.isCompleted = true
    elsif @todo.isCompleted == true then
      @todo.isCompleted = false
    end
    @todo.save
    redirect_to '/'
  end

  def create
  	#render plain: params[:task].inspect
  	@todo = Todo.new(todo_params)
  	@todo.isCompleted = false
  	#render plain: @todo.inspect
  	@todo.save
  	redirect_to '/'
  end

  private def todo_params
  	params.require(:task).permit(:text, :project_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo/create.html.erb
<h1>Todo#create</h1>
<p>Find me in app/views/todo/create.html.erb</p>

app/views/todo/index.html.erb
<div id="header">
	<h1>Задачи</h1>
	<h1><%= link_to '+', '#', id: 'add_task' %></h1>
</div>

<div class="container-fluid">
	<div class="row">
		<% @projects.each do |project| %>
			<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
				<div id="project">
					<h5><%= project.title %></h5>
					<hr>
					<ul>
						<% @todos = project.todos.order(id: :asc).all %>
						<% @todos.each do |todo| %>
				  			<li>
				  				<%= form_for :todo, :html => {:id=>'form_todo'}, url: '/todo/' + todo.id.to_s + '/update', method: 'get' do |form| %>
				  					<% if todo.isCompleted == true then %>
					  					<input type="checkbox" checked>
					  				<% else %>
					  					<input type="checkbox">
					  				<% end %>
					  				<span><%= todo.text %></span>
					  			<% end %>
				  			</li>
				  			<br>
						<% end %>
					</ul>
				</div>
			</div>
		<% end %>
	</div>
</div>

<div style="visibility: hidden" id="new_task">
	<h5>НОВАЯ ЗАДАЧА</h5>
	<hr>
	<div>
		<%= form_for :task, :html => {:id=>'form_task'}, url: todo_create_path do |form| %>
		  	<p>
		    	<%= form.text_field :text, placeholder: 'Новая задача' %>
		  	</p>
		  		<%= form.select :project_id, @projects.map {|u| [u.title, u.id]}  %>
		  	<p>
		  		<%= link_to 'ОТМЕНА', '#', id: 'task_cancel' %>
		  		<%= link_to 'ОК', '#', id: 'task_ok', :onclick=>"document.getElementById('form_task').submit()" %>
		  	</p>
		<% end %>
	</div>
</div>

app/views/todo/update.html.erb
<h1>Todo#update</h1>
<p>Find me in app/views/todo/update.html.erb</p>